### Test Server ###
spring:
  datasource:
    url: ENC(U7vwfK9QHY32OeJOzYUhnGe694ZWH3ObLRNnvR4g0Jm9R02YozH/qHkdPFEqo50UlBQ5HxR9QVwnolyPSYHpOSMuX0AWNbM+)
    username: ENC(+0DjgDE2QzZsE3J22XipNJ85RscOt6Fx)
    password: ENC(+v0mmaUJeFXYNv70/Vi8ZcYUnifhXdVa)

  ### Deploy Server ###
  #spring:
  #  datasource:
  #    url: ENC(jS5X2XunAOd0i+FkDK7iyTtxHZzPJYh/71TfZMcpx/LVW1Py2C5R8h6CMg+z8pdu5Ql4m+IXMiHV8Q6tLhLd1Q==)
  #    username: ENC(EbHNN55IPexGgBFOmnXRROGlVa8RZioT)
  #    password: ENC(zLA8zMUg4VkzQsNnik2Y8DYtjGfRM+ZM)


  ### GMail ###
  mail:
    host: smtp.gmail.com
    port: 465
    username: ENC(YSIukal9W6pIy9Lj9j7Mw50EBj6r1yV0O9IU3IoMh9jREPh2kEdfFQ==)
    password: ENC(dYWX2Og3+sY4n5D+oBM4LYxE8Dtz6DKleAybB+Qwu1M=)
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.ssl.enable: true
    transport:
      protocol: smtp
### Iamport ###
iamport:
  api:
    apiKey: ENC(p/c/h2uRBPxHF59x0Lw/gYq7H08VOYr420uvqiqQ5QY=)
    apiSecret: ENC(ZZL3emNk6kWN/AaJR0Uaq5eDV+WEK4Y0VGpXvbBGr/reVBvtph7u9QJ9G7e5bD7w/UVvar0dDsVao1wFphuw17IpLrXSkHyR5r9/dHQPVR4IyfTQQh3/0Wq/OjEmOysD)
### KakaoMap Api Key ###
kakao:
  map:
    apiKey: ENC(TX1TqMZd776PPtKZaMih/v8Fy5xJqmz/uB1PvunCAZMkEBLmaQBfyYL9x89nPfjJxBQwhGkOmxI=)
  pay:
    apiKey: ENC(GN1Uk9wlmynBoGayMDgkkLpDOq+um8wzjxJieMYSAc260DYwLxfzGSCxXBNnUdo58JbcdTLehfo=)